### ISSUE TITLE
Some objects don't place. (E.g. Oak tree)

### ISSUE THREAD

**Issue by lauren-mods** [heinermann/Valheim_mods#1]
## Description
Some objects don't place. (E.g. Oak tree)

## To Reproduce
1. Install mod
2. Try to build an oak tree
3. 
4. 

## Expected behavior
An oak tree is built 

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*

[Player.log](https://github.com/heinermann/Valheim_mods/files/7959396/Player.log)

##
 Mod list
- Jotunn
- BetterCreative
- Planbuild
- Plant Everything
- [many other mods]

## Version
 - Valheim Version: latest
 - OS: Windows

**Comment by lauren-mods** [comment]
Full Mod List:
 AdditionalRecipes 
 BackpackRedux 
 ConsoleTweaks 
 CraftingFilter 
 MMHOOK 
 PlanBuild 
 RecipeCustomization 
 Advize_CartographySkill.dll 
 Advize_CartographySkill.json 
 Advize_PlantEverything.dll 
 AnimationSpeed.dll 
 AutoSplitStack.dll 
 BackpackRedux.dll 
 BuildingDemolish.dll 
 BuildingRepair.dll 
 ConfigurationManager.dll 
 ConfigurationManager.xml 
 ConsoleTweaks.dll 
 CraftAll.dll 
 CraftingFilter.dll 
 CropReplant.dll 
 CustomContainerSizes.dll 
 CustomGraphicsSettings.dll 
 DeathTweaks.dll 
 Digitalroot.Valheim.SlopeCombatFix.dll 
 DiscardInventoryItem.dll 
 EquipMultipleUtilityItems.dll 
 EZBuild.dll 
 Fish Overhaul.dll 
 GrassTweaks.dll 
 Hearthstone.dll 
 HotbarSwitch.dll 
 ImprovedBuildHud.dll 
 Jotunn.dll 
 LastUsedWeapons.dll 
 MapCoordinateDisplay.dll 
 MapTeleport.dll 
 PassiveForsakenPowers.dll 
 Precise Piece Placement.dll 
 QuickStore.dll 
 RagnarsRokare_CraftToStack.dll 
 RecipeCustomization.dll 
 ReelySpecTackleLure.dll 
 Regeneration.dll 
 RequipMe.dll 
 SeafloorWalkingBoots.dll 
 SimpleSort.dll 
 SKKDisableBossRegeneration.dll 
 SnapPointsMadeEasy.dll 
 TerrainReset.dll 
 TopMining.dll 
 Valheim.CustomRaids.dll 
 Valheim.DisplayBepInExInfo.dll 
 Veinmine.dll 
 WolfPack.dll

**Comment by heinermann** [comment]
Thanks for the issue, this has to do with the Unrestricted Placement setting being disabled by default. I'll investigate enabling clipping for some of these objects with the setting disabled and also enable the setting by default.

**Comment by heinermann** [comment]
Fixed in 98578b5841875 - New version of the mod is uploaded as version 1.0.1.
