### ISSUE TITLE
caverock_ice_pillar issue

### ISSUE THREAD

**Issue by evexavier** [heinermann/Valheim_mods#12]
## Description
Dropped caverock_ice_pillars in world. When I try to log in, I am stuck on the start splash page with lag and am unable to get into the game. There's an incessant warning lagging her game client to the point  of crashing: "[Warning: Unity Log] <mm/dd/yyyy HH:MM:SS>: Double ZNetview when initializing object caverock_ice_pillar(clone).
I am unable to get past the splash screen.

## To Reproduce
1. Log in
2. error occurs and warning continues so I am unable to log in
3. 
4. 

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

*Note: Remove `:heavy_check_mark:` to uncheck.*

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost |  |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina |  |
|| All Prefabs |  |
|| Unrestricted Placement | |
|| No Piece Drops |  |
|| No Placement Delay |  |
|| No Durability Drain | : |

## Expected behavior
...

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*

## Mod list
- Jotunn
- BetterCreative
- 
- 

## Version
 - Valheim Version: 0.207.20
 - OS: [Windows
![20220325134644_1](https://user-images.githubusercontent.com/102381174/160175011-cbaafe8f-2170-4437-930b-341d988891d7.jpg)
[Player.log](https://github.com/heinermann/Valheim_mods/files/8352804/Player.log)
![unitylog](https://user-images.githubusercontent.com/102381174/160175012-96616166-4f01-4aa5-aca6-a50da6a26a49.JPG)
]

**Comment by heinermann** [comment]
Thanks, it will be fixed for mod users in the next version, but maybe not for vanilla users.

**Comment by heinermann** [comment]
New version is up

- [Thunderstore](https://valheim.thunderstore.io/package/Heinermann/BetterCreative/)
- [NexusMods](https://www.nexusmods.com/valheim/mods/1726)

Reopen if your issue still occurs.

**Comment by evexavier** [comment]
thank you. It has allowed me to log in but causes intense lag.
