### ISSUE TITLE
Version 1.20 breaks many things

### ISSUE THREAD

**Issue by dejayc** [heinermann/Valheim_mods#13]
## Description
Version 1.20 has broken so much functional behavior of the plugin that it's hard to document.  For example, signs can no longer be placed on metal cages; they float 1 meter away from all cage surfaces.  The triple-dot ellipsis `...` of the sign is no longer visible when placing it.  The plugin also completely breaks other plugins like PlanBuild, disabling that plugin's keybindings and mode switching.

## To Reproduce
1. Try to place a sign upon a cage.
2. Observe that the sign floats one meter away from the surface of the cage.
3. Observe that the triple-dot ellipsis is no longer visible on the sign when placing it.
4. Observe that BetterCreative completely breaks almost all functionality of PlanBuild.

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | Both states tested |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Expected behavior
...

`...` indeed!

## Log file and Screenshots

[Player.log](https://github.com/heinermann/Valheim_mods/files/8355716/Player.log)

## Mod list
- Jotunn 2.6.0
- BetterCreative 1.20
- PlanBuild 0.9.5 (issues happen with PlanBuild enabled or disabled)
- r2modman 3.1.27

## Version
 - Valheim Version: 2022-02-25 0.207.20
 - OS: Windows 10 Home 21H1 19043.1586

**Comment by heinermann** [comment]
Looking into it.

**Comment by heinermann** [comment]
Updated the mod to 1.2.1 to address the issues mentioned. Feel free to reopen or create a new issue if there are more.

**Comment by dejayc** [comment]
Good work, I appreciate the fast turnaround time on this!
