### ISSUE TITLE
Crashing after updating to versions newer than 1.1.0

### ISSUE THREAD

**Issue by Sinimyn** [heinermann/Valheim_mods#14]
## Description
I can't go beyond the character loading screen, once select my seed and try to load the game crashes. Valheim runs fine with the version 1.1.0 but beyond that it doesn't work. I have tried a few times.

## Log file and Screenshots
[Player.log](https://github.com/heinermann/Valheim_mods/files/8358010/Player.log)

## Mod list
- Jotunn
- BetterCreative
- 
![Mods](https://user-images.githubusercontent.com/102477541/160290749-a9ca2ee2-2e8b-4b5c-bd9d-086554d1378e.PNG)

- 

## Version
 - Valheim Version: 0.207.20
 - OS: Windows

**Comment by heinermann** [comment]
1. Which version of BetterCreative are you using? I released a followup to fix compat issues (1.2.1).
2. Try to narrow it down by
  1. Remove 50% of the mods (except for Jotunn, MMHOOK, and BetterCreative), see if it still crashes.
  2. If it doesn't, remove the ones that worked and then repeat step 1 for the remaining items (50% of the other 50%).
  3. If it does, continue by removing 50% more and then repeat step 1 until only 1 mod is remaining.
3. Please give the BetterCreative mod configuration as well.

**Comment by Sinimyn** [comment]
I have tried both updates 1.2.0 and 1.2.1 and both make me crash when attempting to load into world, hence why I reverted back to version 1.1.0 which works perfectly fine. I believe it has to do with Unity? I do get a small screen popping up but haven't figured out how to screenshot it before the game CTD's. 
I will try to unload mods as you suggested but that will be a day long venture, when I have the time to do so I will and post my results. Otherwise here is the conf for the version I use. 
[Document.docx](https://github.com/heinermann/Valheim_mods/files/8358443/Document.docx)

**Comment by heinermann** [comment]
I've updated it to 1.2.2. It does do some compatibility changes so see if it addresses the issue (I don't think I addressed this issue specifically though).

**Comment by Sinimyn** [comment]
Whatever you did fixed it! Thank you so much. Love the mod!!

**Comment by heinermann** [comment]
Uhhh ok sure! :D
