### ISSUE TITLE
Just don't know How

### ISSUE THREAD

**Issue by Bjorn1337** [heinermann/Valheim_mods#16]
I created a Spawner for GreyDwarf Elites and now I can't delete it. Don't think it's a bug, I just don't know how. 
Can you tell me how to do that?
Otherwise, I love the Mod. 
## Feature Request 
In *BetterCreative*, I'd like to see...

**Comment by heinermann** [comment]
Select the spawner again with the hammer and use the delete key to delete nearby objects of the same type.

**Comment by Bjorn1337** [comment]
Thanks, Sorry to have bothered you with this. I just wasn't getting it.
Needed it spelled out for me I guess.
