### ISSUE TITLE
Stopped working after Valheim update

### ISSUE THREAD

**Issue by Frog3220** [heinermann/Valheim_mods#21]
## Description
Hello, again! I've been enjoying the mod for a while, but after the Valheim update last month it stopped working - probably because of a setting issue. I use Vortex and did a slew of updates, elevations, etc, and apparently mucked something up, as the "mod settings" no longer appeared at the start menu.

I reinstalled Valheim (from Steam), wiped all the mods and reinstalled Vortex, then reinstalled Jotunn and BetterCreative. Attached is a screenshot of Vortex to show the mods I've got, and the player.log file.

In Steam, the Launch Options contains "-console", and the integrity of local files verified.

The Installation instructions on nexusmods indicate 'copy contents or use mod manager' and I presume Vortex counts. Are there more detailed instructions or a troubleshooting guide?

Thank you.
-Jar

## Log file and Screenshots

![__vortexmods01](https://user-images.githubusercontent.com/100496409/176997165-ed19bafd-c3c5-46a1-a61a-cdc7723edbf5.png)

[Player.log](https://github.com/heinermann/Valheim_mods/files/9032848/Player.log)

## Mod list
- Jotunn
- BetterCreative
- denikson-BepInExPack_Valheim-5.4.1901.zip
- Configuration Manager

## Version
 - Valheim Version: not sure - installed yesterday via Steam
 - OS: [Windows/Mac/Linux] Windows 10 Pro Version 10.0.19044 Build 19044

**Comment by heinermann** [comment]
Thanks I will take a look.

**Comment by heinermann** [comment]
It appears to be working just fine, but Jotunn has removed mod settings for everyone, I don't know why they did that yet.

**Comment by heinermann** [comment]
One alternative is you can try using [this configuration manager](https://valheim.thunderstore.io/package/Azumatt/Official_BepInEx_ConfigurationManager/).

**Comment by heinermann** [comment]
According to Jotunn developers the in-game mod settings menu was a frequent pain point during game patches, so they removed it. You will have to complain to them or use the configuration manager mod.

I have tested it and the mod otherwise appears to be working fine.

**Comment by Frog3220** [comment]
*heh* Thank you - the advice "Hit F1" did the job. I appreciate your looking into the situation.

Now I'm struggling to get my saved world to load - it keeps crashing the game. Might you be up for figuring that one out?

**Comment by Frog3220** [comment]
![__Untitled](https://user-images.githubusercontent.com/100496409/177019773-03748df6-d9f3-4ed1-92d0-45fc7c05beab.png)

**Comment by heinermann** [comment]
Upload your save somewhere and maybe I'll take a look but I can't promise anything.

**Comment by Frog3220** [comment]
Thank you. If it helps, I'll hire you to get it working - I put a lot of time into this and I'm willing to reimburse you for yours, to get it back.
Here's what I hope is a link to the March backups that work, and the May & July ones that don't: https://drive.google.com/drive/folders/11CKDbGtAYDNoutpQP39MVGFtRuOYmI7p?usp=sharing

Please let me know if the link doesn't work - it's my first time attempting to create a shared drive.

**Comment by iocron** [comment]
Hello, I've just tried a fresh install by using the Mod Manager (Thunderstore) and tried a manual installation to verify the problem, then when I start Valheim as usual, there seem to be no changes. I am using BepInExPack Valheim 5.4.1901, Jotun 2.7.0 and BetterCreative 1.2.3. There seem to be some problems with the latest Jotun and/or BepInExPack? Is there anything else I can to make this great mod work?

**Comment by iocron** [comment]
I still have the problem that the icons look all greenish in the build menu. Is there anything to fix this?

**Comment by Frog3220** [comment]
The color just happens sometimes - I've gotten green and orange - and generally goes away with a restart.

**Comment by Frog3220** [comment]
The Reddit user MayaOmkara pointed me to a solution, using the guide to a crashing Valhaim at https://www.reddit.com/r/valheim/comments/uq9b8x/my_valheim_is_crashing_fix_for_crash_guide/ - number seven was it, as I'd indeed placed a dozen or so of the guard stones. The kirilloid site removed them and after a bit of fiddling to get the new file in the correct location, it works.
*phew*

**Comment by heinermann** [comment]
Since you got everything working (I think) I'll close this now.
