### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by RetroFrito** [heinermann/Valheim_mods#22]
![Capture](https://user-images.githubusercontent.com/115475676/194873389-201f4f0d-cb2c-45a3-9d8f-de03c03872c2.JPG)
## Description
*After a fresh install I get this error. I followed the directions of being sure to have Jotun, Bepin, and ModSettings, and installed via my "favorite mod manager" in this case Vortex.*

## To Reproduce
1. Install and enable mod
2. Launch game
3. Select server and enter password
4. Error is displayed

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

## Mod list
![Capture2](https://user-images.githubusercontent.com/115475676/194875118-2cbb9727-180a-4760-83a6-84bd573d9836.JPG)

- 

## Version
 - Valheim Version: 0.211.8
 - OS: [Windows 10]

**Comment by heinermann** [comment]
I will update it this week.

**Comment by heinermann** [comment]
Wait is the mod also bring run on your server?

**Comment by RetroFrito** [comment]
I do not have any mods on my server. I did not install this one on it because I did not see that mentioned in the instructions

**Comment by heinermann** [comment]
Added a note in https://github.com/heinermann/Valheim_mods/commit/37910af886391a8fdebd88256750c934daf24621 .

**Comment by RetroFrito** [comment]
I am still getting the same error. Here are the steps I've taken since your update to the notes:

I've installed BepinEX into the dedicated server folder. In the plugins folder located there, I have added the BetterCreative.dll and all the Jotunn.dll files.

**Comment by RetroFrito** [comment]
I'm closing this issue and wanted to offer an apology, I realized this was completely my mistake. I had the BepinEX files installed incorrectly into the server directory. Once I corrected this, the mods work as expected. Sorry if this wasted much of your time.
