### ISSUE TITLE
Compatibility force mode config flag

### ISSUE THREAD

**Issue by nilsroesel** [heinermann/Valheim_mods#26]
## Feature Request 
The removal of the version compatibility force mode if possible.
As far as i tested the features seem to be completely client sided, at least the hammer extension.
Adding a statement in the config to enable/disable it would be nice

**Comment by heinermann** [comment]
The need to have it installed on the server is an intentional design to prevent cheaters from ruining server and I will not be changing it, nor will I allow forks of the code that circumvent that feature.

**Comment by nilsroesel** [comment]
Ok, maybe you can help me then:
I was trying to mod something similar before and want to stay vanilla compatible on the same time.
I basically only want to be able to build pieces, which are not buildable (such as dverger furniture)
But this always resulted in invisible pieces for clients which does not have the mod
