### ISSUE TITLE
Vertical and Horizontal Rotation of Items

### ISSUE THREAD

**Issue by Zenner1** [heinermann/Valheim_mods#27]
I'm really glad I found this mod.
I only wanted to add a few vines that despawned on me too quickly when building.
Is there a way to rotate them on the horizontal axis? In other words, a way to place them flat again roofs of various angles, and not just fon walls. Or perhaps on floors?
Maybe I missed something obvious.
Thanks! 

EDIT: Found an obvious solution :)
https://www.nexusmods.com/valheim/mods/202?tab=description
This mod will allow rotation of objects on all 3 axes. (I like how axes is the plural of axis. And this a Viking game...)

**Comment by heinermann** [comment]
Yes, axis rotation is not a feature of the mod.
