### ISSUE TITLE
please update the mod

### ISSUE THREAD

**Issue by kingxenan** [heinermann/Valheim_mods#28]
## Description
*(Describe the bug)*

## To Reproduce
1. 
2. 
3. 
4. 

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

*Note: Remove `:heavy_check_mark:` to uncheck.*

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | :heavy_check_mark: |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Expected behavior
...

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*

## Mod list
- Jotunn
- BetterCreative
- 
- 

## Version
 - Valheim Version: ???
 - OS: [Windows/Mac/Linux]

**Comment by kingxenan** [comment]
i get shaders bug with krumpac reforged mods

**Comment by kingxenan** [comment]
and t ybtw for the best world building mod ever made for this game can't live without it

**Comment by kingxenan** [comment]
maybe join discord and try to fix it  with him https://discord.gg/QtXgjvG8

**Comment by heinermann** [comment]
That sounds more like a problem with the other mod. Closing this since there's no info.
