### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Kalwards** [heinermann/Valheim_mods#31]
## Description
I have installed everything according to the instructions, but I do not automatically enter the game in creative mode. When I activate the console commands the items are not added to the crafting menu. What am I doing wrong.

## To Reproduce
1. Jotunn already installed
2. Installed from Nexus via Vortex Mod Manager
4. Nothing
5. Install manually
6. Nothing 

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.
![BetterCreativeBUG](https://github.com/heinermann/Valheim_mods/assets/137318321/6e009fe3-8c65-4681-93dd-84f0a9b289fd)

*Note: Remove `:heavy_check_mark:` to uncheck.*

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | :heavy_check_mark: |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Expected behavior
...

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*

## Mod list
- Jotunn
- BetterCreative
- ValheimPlus
- Auto Fuel
- BepinEx Configuration manager
- Better Archery
- Better Creative
- Craft from containers
- Endurance
- Equipment and quickslots
- farm grid
- heightmap unlimited
- massfarming
- Plant Everything
- Slope hit fix MAIN
- Unrestricted Portals
- ValheimRAFT
- XPortal
- 

## Version
 - Valheim Version: 0.216.9
 - OS: [Windows]

**Comment by heinermann** [comment]
What happens if it's just Jotunn and Better Creative?

**Comment by Kalwards** [comment]
Ah ha! It works!! I should have known this would solve it... Thanks for your speedy response!
