### ISSUE TITLE
Missing Asset Tabs

### ISSUE THREAD

**Issue by SmittySurvival** [heinermann/Valheim_mods#33]
## Description
*Hammer no longer has additional asset tabs*

## To Reproduce
1. Issue exists from load. Mod shows in configurations, but the tabs w/ game assets are missing
2. 
3. 
4. 

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

*Note: Remove `:heavy_check_mark:` to uncheck.*

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | :heavy_check_mark: |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Expected behavior
Normally Additional tabs show in the hammer menu (i.e Destructibles, NPCs, etc.)

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*

## Mod list
- Jotunn
- BetterCreative
- 
- 

## Version
 - Valheim Version: ???
 - OS: [Windows/Mac/Linux]

**Comment by heinermann** [comment]
Hello, there's nothing wrong with the mod. The problem is with Jotunn. You will have to downgrade to Jotunn 2.12.7 as the regression happened in Jotunn 2.13. In the meantime I've asked for a solution.

**Comment by heinermann** [comment]
Thanks to Margmas for a quick solution, I have updated the mod to 1.4.1 and the build categories should be included again using the latest Jotunn version.
