### ISSUE TITLE
New prefab tabs not seen in hammer's build list.

### ISSUE THREAD

**Issue by Wedgenet** [heinermann/Valheim_mods#34]
## Description
* Additional tabs with new build prefabs are not available.  Prefabs not normally available are seen (e.g. all seasonal items) but none that are not categorized in the vanilla game's build tabs.*  (Possible PEBCAK if I missed a config option or hotkey?)

## To Reproduce
1. Enable BetterCreate, Jotunn in Thunderstore Mod Manager, Launch Valheim via Thunderstore
2. Load Map (Default Settings except "No Build Cost" enabled)
3. Equip Hammer and view build list (attached screenshot)
4. 

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

BetterCreative config file pasted below.

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | :heavy_check_mark: |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Expected behavior
Additional tabs in the build menu available with prefabs made available by BetterCreative.

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*

## Mod list
- Jotunn v2.14.1
- BetterCreative v1.4.0

## Version
 - Valheim Version: 0.217.14(n-12) -- Steam App ID 892970 Build ID 11978864
 - OS: Windows

## Configuration and player.log

```
## Settings file was created by plugin BetterCreative v1.4.0
## Plugin GUID: com.heinermann.bettercreative

[Command States]

## Enable devcommands automatically. Required for other commands to function.
# Setting type: Boolean
# Default value: true
devcommands = true

## No build cost, unlocks everything.
# Setting type: Boolean
# Default value: true
nocost = true

## Makes it so you don't take damage from monsters.
# Setting type: Boolean
# Default value: true
god = true

## Prevents mobs from seeing you.
# Setting type: Boolean
![Capture](https://github.com/heinermann/Valheim_mods/assets/21322530/57110289-c0bd-4caa-8543-a797f5a4d05d)

# Default value: true
ghost = true

## Enables fly mode and debug hotkeys.
# Setting type: Boolean
# Default value: true
debugmode = true

[Hotkeys]

## Warning: default (ctrl+z) conflicts with sneak and fly.
# Setting type: KeyboardShortcut
# Default value: Z + LeftControl
Undo = Z + LeftControl

## Alternative.
# Setting type: KeyboardShortcut
# Default value: 
Undo (alt) = 

## Warning: default (ctrl+shift+z) conflicts with sneak and fly.
# Setting type: KeyboardShortcut
# Default value: Z + LeftShift + LeftControl
Redo = Z + LeftShift + LeftControl

## Alternative.
# Setting type: KeyboardShortcut
# Default value: Y + LeftControl
Redo (alt) = Y + LeftControl

## Destroys all prefabs that match the currently selected piece in the area.
# Setting type: KeyboardShortcut
# Default value: Delete
Delete = Delete

# Setting type: KeyboardShortcut
# Default value: 
Delete (alt) = 

[Improvements]

## Can always perform stamina actions regardless of stamina amount.
# Setting type: Boolean
# Default value: true
Unlimited Stamina = true

## Allow placement of all functional prefabs. (Requires restart to take effect)
# Setting type: Boolean
# Default value: true
All Prefabs = true

## Allow unrestricted placements (no collision, campfire on wood, etc). Note: Disabling this won't allow placement of some objects. (Requires restart to take effect)
# Setting type: Boolean
# Default value: true
Unrestricted Placement = true

## Don't drop materials when pieces are destroyed.
# Setting type: Boolean
# Default value: true
No Piece Drops = true

## No cooldowns for the hammer, cultivator, or hoe. (Requires restart to take effect)
# Setting type: Boolean
# Default value: true
No Placement Delay = true

## Tools don't lose durability. (Requires restart to take effect)
# Setting type: Boolean
# Default value: true
No Durability Drain = true

## No effect when surpassing maximum carry weight
# Setting type: Boolean
# Default value: true
No Encumbered = true

## No popup message when unlocking a recipe
# Setting type: Boolean
# Default value: true
No Unlock Messages = true

## Range to delete objects with the delete key. This is the radius from the placement ghost's center.
# Setting type: Int32
# Default value: 5
Delete Range = 5
```
![Capture](https://github.com/heinermann/Valheim_mods/assets/21322530/f400cd82-caae-4500-a9dd-8c04dce678d8)
[Player.log](https://github.com/heinermann/Valheim_mods/files/12743824/Player.log)

**Comment by Wedgenet** [comment]
I just noticed that this is probably a duplicate of #33 I'll leave it alive in case the additional information here is useful.

**Comment by heinermann** [comment]
You playing on main or beta?

**Comment by Wedgenet** [comment]
> You playing on main or beta?

I'm not sure if  you mean main/beta for Valheim or a beta branch of BetterCreative, so I'll try to provide both as best I can.

Valheim is running the current main build distributed by steam. I have not opted into any beta builds in Steam properties menus for Valheim.  (0.217.14(n-12) -- Steam App ID 892970 Build ID 11978864)

Better Creative is the version distributed by Thunderstore as 1.4.0.  I don't see any option for main/beta branches here, so I assume it's the main branch, but in case it helps the BetterCreative.dll has a MD5 checksum of `1ffd121f59a2304ce11225e0f290b111`

Here's what windows tells me about the metadata in the dll: 

![Capture](https://github.com/heinermann/Valheim_mods/assets/21322530/4985a7ab-f020-4406-828e-f5b9c50df53f)

Please let me know if I can provide any additional information or help test anything specific.  Thank you for the prompt reply.

**Comment by heinermann** [comment]
Hello, there's nothing wrong with the mod. The problem is with Jotunn. You will have to downgrade to Jotunn 2.12.7 as the regression happened in Jotunn 2.13. In the meantime I've asked for a solution.

**Comment by heinermann** [comment]
Thanks to Margmas for a quick solution, I have updated the mod to 1.4.1 and the build categories should be included again using the latest Jotunn version.
