### ISSUE TITLE
Hammer Delete Object Error

### ISSUE THREAD

**Issue by MikeFoxy** [heinermann/Valheim_mods#36]
## Description
While playing on the Ashlands PTB, attempting to delete / remove / destroy any object while using the Hammer results in the following error code: 

[Error  : Unity Log] MissingMethodException: Method not found: void .Piece.DropResources()
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::RemovePiece>(Player)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

This issue occurs regardless of whether the "No Piece Drops" setting is enabled or disabled. No other settings seemed to affect the error either.

## To Reproduce
1. Equip the Hammer
2. Attempt to delete / break / remove any object using the Hammer

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

*Note: Remove `:heavy_check_mark:` to uncheck.*

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | :heavy_check_mark: |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Mod list

- Irrelevant, bug only occurs when Better Creative Mode is enabled. The mod was perfectly functional on the previous branch with my current mod list.

## Version
 - Valheim Version: Ashlands PTB
 - OS: [Windows 10]

**Comment by heinermann** [comment]
Thanks I will look into it by this weekend.

**Comment by heinermann** [comment]
I've updated it and uploaded an alternate (non-main) file for the Ashlands PTB: https://www.nexusmods.com/valheim/mods/1726?tab=files

Let me know if there are any issues.
