### ISSUE TITLE
Ashlands not supported

### ISSUE THREAD

**Issue by Wmonnh6** [heinermann/Valheim_mods#38]
## Description
*(Describe the bug)*

## To Reproduce
1. Install mod, have all creative powers turned on
2. load ashlands  update version of game
3. try to build something
4. try to break that build piece 

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

*Note: Remove `:heavy_check_mark:` to uncheck.*

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | :heavy_check_mark: |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Expected behavior
... should be able to build and break build pieces without having their materials drop but it gives this error when trying to break the build piece 
[Error  : Unity Log] MissingMethodException: Method not found: void .Piece.DropResources()
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::RemovePiece>(Player)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*
[Player.log](https://github.com/heinermann/Valheim_mods/files/15358019/Player.log)

## Mod list
- Jotunn
- BetterCreative
- AutoRepair
- AzuAutoStore
- BepInExPack_Valheim
- BetterCreative
- BetterLadders
- Build_In_Dungeons
- Build_Near_Locations
- CropReplant
- CustomChestName
- EquipmentAndQuickSlots
- FarmGrid
- FloatingItems
- GumshoeTimerSuite
- HookGenPatcher
- Infinity_Hammer
- Infinity_Tools
- Item_Stand_All_Items
- M3TO_Gizmo_Reloaded
- More_Vanilla_Build_Prefabs
- MultiUserChest
- OCDheim
- PlantAnywhere
- PlantEasily
- PlantEverything
- Recycle_N_Reclaim
- RevampedTrader
- RockTheBoat
- SearsCatalog
- Server_devcommands
- SmarterContainers
- TeleportEverything
- TorchesEternal
- TradersExtended
- TrashItems
- UseEquipmentInWater
- ValheimFPSBoost
- ValheimPlus
- ValheimPlus_Grantapher_Temporary
- ValheimRAFT
- World_Edit_Commands

## Version
 - Valheim Version: 0.218.15 (Ashlands Update)
 - OS: [Windows/Mac/Linux]
 - Windows

**Comment by Wmonnh6** [comment]
I also cannot download the Ashlands PTB version as it is not on thunderstore which is what I use for modding please help.

**Comment by heinermann** [comment]
Updated the main file on Nexus and Thunderstore.
