### ISSUE TITLE
Restricted Placement Option

### ISSUE THREAD

**Issue by AnnieR98** [heinermann/Valheim_mods#4]
## Feature Request 
In *BetterCreative*, I'd like to see...
if u could enable the option restriction placement for all items to place that would be great love the mod just want some stable placement option!

**Comment by heinermann** [comment]
Can you elaborate on this? What do you mean by restricted placement and for which items?

**Comment by AnnieR98** [comment]
Yes so for example when I want to place any block from items you have added for example the mossy rock slab  can place it in the middle of a tree. I just want placable items to be place via game properties, like when it highlights red while trying to place something and having to make the terrain anooth.

**Comment by heinermann** [comment]
They don't have any placement properties in vanilla. I would have to create new ones, it's not something I'll be working on in the near term.

**Comment by AnnieR98** [comment]
UnrestrictedPlacement = Config.Bind("Improvements", "Unrestricted Placement", true, "Allow unrestricted placements (no collision, campfire on wood, etc). Note: Disabling this won't allow placement of some objects. (Requires restart to take effect)");

can u change “unrestricted placement true” to . false

**Comment by heinermann** [comment]
That's a config option for you to change in the mod settings.

**Comment by AnnieR98** [comment]
Alright in that case when I do change it  I can’t seem to save it always has a problem...my question is what else am I suppose to change in order to save that change?

**Comment by heinermann** [comment]
You change it in the mod settings then restart your game.

<img width="318" alt="2022-01-30 05_13_27-Valheim" src="https://user-images.githubusercontent.com/1966366/151701196-f3244fab-385f-4c34-8ed7-097aababcf8a.png">

<img width="671" alt="2022-01-30 05_13_43-Valheim" src="https://user-images.githubusercontent.com/1966366/151701197-791848a8-9d6a-4808-933e-5481661d44fa.png">

**Comment by AnnieR98** [comment]
OMG THANK YOU!!!!
