### ISSUE TITLE
Delete things.

### ISSUE THREAD

**Issue by ghost** [heinermann/Valheim_mods#40]
## Description
*(Describe the bug)*

Since the Ashland update i havent been able to delete things i place in the same way i delete things without the mod, like in vanilla i just right click to delete things. No i cant even delete all thing like big rocks and stuff

## To Reproduce
1. 
2. 
3. 
4. 

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

*Note: Remove `:heavy_check_mark:` to uncheck.*

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | :heavy_check_mark: |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Expected behavior
...

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*

## Mod list
- Jotunn
- BetterCreative
- 
- 

## Version
 - Valheim Version: ???
 - OS: [Windows/Mac/Linux]

**Comment by heinermann** [comment]
Dupe https://github.com/heinermann/Valheim_mods/issues/38
