### ISSUE TITLE
How to access in-game menu

### ISSUE THREAD

**Issue by ErnieParrow** [heinermann/Valheim_mods#9]
## Description
Your instructions to install the mod doesn't say how to use the mod.  How do we use the commands via chat?  How do we access the in-game options?

## To Reproduce
1. 
2. 
3. 
4. 

### Mod Settings
In order to reproduce the issue, the following mod configuration was used.

*Note: Remove `:heavy_check_mark:` to uncheck.*

||||
|---|---|---|
| **Command States** |
|| devcommands | :heavy_check_mark: |
|| nocost | :heavy_check_mark: |
|| god | :heavy_check_mark: |
|| ghost | :heavy_check_mark: |
|| debugmode | :heavy_check_mark: |
| **Improvements** |
|| Unlimited Stamina | :heavy_check_mark: |
|| All Prefabs | :heavy_check_mark: |
|| Unrestricted Placement | :heavy_check_mark: |
|| No Piece Drops | :heavy_check_mark: |
|| No Placement Delay | :heavy_check_mark: |
|| No Durability Drain | :heavy_check_mark: |

## Expected behavior
...

## Log file and Screenshots
*(Upload log file and/or screenshots if relevant)*
*On Windows, the logfile should be located at `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim\Player.log`*

## Mod list
- Jotunn
- BetterCreative
- 
- 

## Version
 - Valheim Version: ???
 - OS: [Windows/Mac/Linux]

**Comment by heinermann** [comment]
The mod just works, you don't use the chat or anything, it's just apparent. There is a menu option for mod settings...
